## Lesson 1: Creating, Reading & Writing

In [2]:
import pandas as pd

### Creating data

There are two core objects in pandas: the **DataFrame** and the **Series**.

#### DataFrame

A DataFrame is a table. It contains an array of individual entries, each of
which has a certain value. Each entry corresponds to a row (or record) and a column.

In [4]:
pd.DataFrame({'Yes': [12, 24], 'No': [13, 26]})

   Yes  No
0   12  13
1   24  26

In this example, the "0, No" entry has the value of 13. The "0, Yes" entry has a value of 12, and so on.  DataFrame entries are not limited to integers. For instance, here's a DataFrame whose values are strings:

In [5]:
pd.DataFrame({'Sheygs' : ['I loved it', 'It was sweet'], 'John': ['Pretty good', 'Bland']})

         Sheygs         John
0    I loved it  Pretty good
1  It was sweet        Bland

The dictionary-list constructor assigns values to the column labels,
but just uses an ascending count from 0 (0, 1, 2, 3, ...) for the row labels.
Sometimes this is OK, but oftentimes we will want to assign these labels ourselves.
The list of row labels used in a DataFrame is known as an **index**.
We can assign values to it by using an `index` parameter in our constructor:

In [23]:
pd.DataFrame({'Sheygs': ['I loved it', 'It was sweet'], 'John': ['Pretty good', 'Bland']}, index=['Product A', 'Product B'])

                 Sheygs         John
Product A    I loved it  Pretty good
Product B  It was sweet        Bland

#### Series

It is a sequence of data values. If DataFrame is a table, a Series is a list

In [ ]:
pd.Series([20, 25, 30, 40])

0    1
1    2
2    3
3    4
dtype: int64

A Series is, in essence, a single column of a DataFrame.
So you can assign row labels to the Series the same way as before,
using an `index` parameter. However, a Series does not have a
column name, it only has one overall `name`:

In [30]:
pd.Series([20, 25, 30, 40], index=['2014 Sales', '2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2014 Sales    20
2015 Sales    25
2016 Sales    30
2017 Sales    40
Name: Product A, dtype: int64

**Note**: A dataFrame is actually just a bunch of "Series" glued together.

### Reading Data Files

In [6]:
reviews = pd.read_csv('../pandas/datasets/winemag-data-130k-v2.csv')

We can use the `shape` attribute to check how large the resulting DataFrame is:

In [7]:
# About 130,000 records split across 14 columns
reviews.shape

(129971, 14)

We can examine the contents of the resultant DataFrame using the `head()` command, which grabs the first five rows:

In [8]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

The `pd.read_csv()` function is well-endowed, with over 30 optional parameters you can specify.
For example, you can see in this dataset that the CSV file has a built-in index,
which pandas did not pick up on automatically. To make pandas use that column for the index
(instead of creating a new one from scratch), we can specify an `index_col`.

In [9]:
reviews = pd.read_csv('../pandas/datasets/winemag-data-130k-v2.csv', index_col=0)

reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks